package priv.guochun.psmc.system.common.log.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSysOperLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public TSysOperLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameIsNull() {
            addCriterion("log_sub_type_name is null");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameIsNotNull() {
            addCriterion("log_sub_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameEqualTo(String value) {
            addCriterion("log_sub_type_name =", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameNotEqualTo(String value) {
            addCriterion("log_sub_type_name <>", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameGreaterThan(String value) {
            addCriterion("log_sub_type_name >", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("log_sub_type_name >=", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameLessThan(String value) {
            addCriterion("log_sub_type_name <", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameLessThanOrEqualTo(String value) {
            addCriterion("log_sub_type_name <=", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameLike(String value) {
            addCriterion("log_sub_type_name like", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameNotLike(String value) {
            addCriterion("log_sub_type_name not like", value, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameIn(List<String> values) {
            addCriterion("log_sub_type_name in", values, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameNotIn(List<String> values) {
            addCriterion("log_sub_type_name not in", values, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameBetween(String value1, String value2) {
            addCriterion("log_sub_type_name between", value1, value2, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNameNotBetween(String value1, String value2) {
            addCriterion("log_sub_type_name not between", value1, value2, "logSubTypeName");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeIsNull() {
            addCriterion("log_sub_type is null");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeIsNotNull() {
            addCriterion("log_sub_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeEqualTo(BigDecimal value) {
            addCriterion("log_sub_type =", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNotEqualTo(BigDecimal value) {
            addCriterion("log_sub_type <>", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeGreaterThan(BigDecimal value) {
            addCriterion("log_sub_type >", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("log_sub_type >=", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeLessThan(BigDecimal value) {
            addCriterion("log_sub_type <", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("log_sub_type <=", value, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeIn(List<BigDecimal> values) {
            addCriterion("log_sub_type in", values, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNotIn(List<BigDecimal> values) {
            addCriterion("log_sub_type not in", values, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("log_sub_type between", value1, value2, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogSubTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("log_sub_type not between", value1, value2, "logSubType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameIsNull() {
            addCriterion("log_type_name is null");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameIsNotNull() {
            addCriterion("log_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameEqualTo(String value) {
            addCriterion("log_type_name =", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameNotEqualTo(String value) {
            addCriterion("log_type_name <>", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameGreaterThan(String value) {
            addCriterion("log_type_name >", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("log_type_name >=", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameLessThan(String value) {
            addCriterion("log_type_name <", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameLessThanOrEqualTo(String value) {
            addCriterion("log_type_name <=", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameLike(String value) {
            addCriterion("log_type_name like", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameNotLike(String value) {
            addCriterion("log_type_name not like", value, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameIn(List<String> values) {
            addCriterion("log_type_name in", values, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameNotIn(List<String> values) {
            addCriterion("log_type_name not in", values, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameBetween(String value1, String value2) {
            addCriterion("log_type_name between", value1, value2, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeNameNotBetween(String value1, String value2) {
            addCriterion("log_type_name not between", value1, value2, "logTypeName");
            return (Criteria) this;
        }

        public Criteria andLogTypeIsNull() {
            addCriterion("log_type is null");
            return (Criteria) this;
        }

        public Criteria andLogTypeIsNotNull() {
            addCriterion("log_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogTypeEqualTo(BigDecimal value) {
            addCriterion("log_type =", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotEqualTo(BigDecimal value) {
            addCriterion("log_type <>", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeGreaterThan(BigDecimal value) {
            addCriterion("log_type >", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("log_type >=", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeLessThan(BigDecimal value) {
            addCriterion("log_type <", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("log_type <=", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeIn(List<BigDecimal> values) {
            addCriterion("log_type in", values, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotIn(List<BigDecimal> values) {
            addCriterion("log_type not in", values, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("log_type between", value1, value2, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("log_type not between", value1, value2, "logType");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidIsNull() {
            addCriterion("bussiness_uuid is null");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidIsNotNull() {
            addCriterion("bussiness_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidEqualTo(String value) {
            addCriterion("bussiness_uuid =", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidNotEqualTo(String value) {
            addCriterion("bussiness_uuid <>", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidGreaterThan(String value) {
            addCriterion("bussiness_uuid >", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidGreaterThanOrEqualTo(String value) {
            addCriterion("bussiness_uuid >=", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidLessThan(String value) {
            addCriterion("bussiness_uuid <", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidLessThanOrEqualTo(String value) {
            addCriterion("bussiness_uuid <=", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidLike(String value) {
            addCriterion("bussiness_uuid like", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidNotLike(String value) {
            addCriterion("bussiness_uuid not like", value, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidIn(List<String> values) {
            addCriterion("bussiness_uuid in", values, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidNotIn(List<String> values) {
            addCriterion("bussiness_uuid not in", values, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidBetween(String value1, String value2) {
            addCriterion("bussiness_uuid between", value1, value2, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andBussinessUuidNotBetween(String value1, String value2) {
            addCriterion("bussiness_uuid not between", value1, value2, "bussinessUuid");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("operid is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("operid is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("operid =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("operid <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("operid >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("operid >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("operid <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("operid <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("operid like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("operid not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("operid in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("operid not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("operid between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("operid not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNull() {
            addCriterion("opername is null");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNotNull() {
            addCriterion("opername is not null");
            return (Criteria) this;
        }

        public Criteria andOpernameEqualTo(String value) {
            addCriterion("opername =", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotEqualTo(String value) {
            addCriterion("opername <>", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThan(String value) {
            addCriterion("opername >", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThanOrEqualTo(String value) {
            addCriterion("opername >=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThan(String value) {
            addCriterion("opername <", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThanOrEqualTo(String value) {
            addCriterion("opername <=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLike(String value) {
            addCriterion("opername like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotLike(String value) {
            addCriterion("opername not like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameIn(List<String> values) {
            addCriterion("opername in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotIn(List<String> values) {
            addCriterion("opername not in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameBetween(String value1, String value2) {
            addCriterion("opername between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotBetween(String value1, String value2) {
            addCriterion("opername not between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("oper_date is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("oper_date is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(Date value) {
            addCriterion("oper_date =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(Date value) {
            addCriterion("oper_date <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(Date value) {
            addCriterion("oper_date >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
            addCriterion("oper_date >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(Date value) {
            addCriterion("oper_date <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(Date value) {
            addCriterion("oper_date <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<Date> values) {
            addCriterion("oper_date in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<Date> values) {
            addCriterion("oper_date not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(Date value1, Date value2) {
            addCriterion("oper_date between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(Date value1, Date value2) {
            addCriterion("oper_date not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperInputIsNull() {
            addCriterion("oper_input is null");
            return (Criteria) this;
        }

        public Criteria andOperInputIsNotNull() {
            addCriterion("oper_input is not null");
            return (Criteria) this;
        }

        public Criteria andOperInputEqualTo(String value) {
            addCriterion("oper_input =", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputNotEqualTo(String value) {
            addCriterion("oper_input <>", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputGreaterThan(String value) {
            addCriterion("oper_input >", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputGreaterThanOrEqualTo(String value) {
            addCriterion("oper_input >=", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputLessThan(String value) {
            addCriterion("oper_input <", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputLessThanOrEqualTo(String value) {
            addCriterion("oper_input <=", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputLike(String value) {
            addCriterion("oper_input like", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputNotLike(String value) {
            addCriterion("oper_input not like", value, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputIn(List<String> values) {
            addCriterion("oper_input in", values, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputNotIn(List<String> values) {
            addCriterion("oper_input not in", values, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputBetween(String value1, String value2) {
            addCriterion("oper_input between", value1, value2, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperInputNotBetween(String value1, String value2) {
            addCriterion("oper_input not between", value1, value2, "operInput");
            return (Criteria) this;
        }

        public Criteria andOperOutputIsNull() {
            addCriterion("oper_output is null");
            return (Criteria) this;
        }

        public Criteria andOperOutputIsNotNull() {
            addCriterion("oper_output is not null");
            return (Criteria) this;
        }

        public Criteria andOperOutputEqualTo(String value) {
            addCriterion("oper_output =", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputNotEqualTo(String value) {
            addCriterion("oper_output <>", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputGreaterThan(String value) {
            addCriterion("oper_output >", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputGreaterThanOrEqualTo(String value) {
            addCriterion("oper_output >=", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputLessThan(String value) {
            addCriterion("oper_output <", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputLessThanOrEqualTo(String value) {
            addCriterion("oper_output <=", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputLike(String value) {
            addCriterion("oper_output like", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputNotLike(String value) {
            addCriterion("oper_output not like", value, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputIn(List<String> values) {
            addCriterion("oper_output in", values, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputNotIn(List<String> values) {
            addCriterion("oper_output not in", values, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputBetween(String value1, String value2) {
            addCriterion("oper_output between", value1, value2, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperOutputNotBetween(String value1, String value2) {
            addCriterion("oper_output not between", value1, value2, "operOutput");
            return (Criteria) this;
        }

        public Criteria andOperResultDescIsNull() {
            addCriterion("oper_result_desc is null");
            return (Criteria) this;
        }

        public Criteria andOperResultDescIsNotNull() {
            addCriterion("oper_result_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOperResultDescEqualTo(String value) {
            addCriterion("oper_result_desc =", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescNotEqualTo(String value) {
            addCriterion("oper_result_desc <>", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescGreaterThan(String value) {
            addCriterion("oper_result_desc >", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescGreaterThanOrEqualTo(String value) {
            addCriterion("oper_result_desc >=", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescLessThan(String value) {
            addCriterion("oper_result_desc <", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescLessThanOrEqualTo(String value) {
            addCriterion("oper_result_desc <=", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescLike(String value) {
            addCriterion("oper_result_desc like", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescNotLike(String value) {
            addCriterion("oper_result_desc not like", value, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescIn(List<String> values) {
            addCriterion("oper_result_desc in", values, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescNotIn(List<String> values) {
            addCriterion("oper_result_desc not in", values, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescBetween(String value1, String value2) {
            addCriterion("oper_result_desc between", value1, value2, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultDescNotBetween(String value1, String value2) {
            addCriterion("oper_result_desc not between", value1, value2, "operResultDesc");
            return (Criteria) this;
        }

        public Criteria andOperResultIsNull() {
            addCriterion("oper_result is null");
            return (Criteria) this;
        }

        public Criteria andOperResultIsNotNull() {
            addCriterion("oper_result is not null");
            return (Criteria) this;
        }

        public Criteria andOperResultEqualTo(Short value) {
            addCriterion("oper_result =", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultNotEqualTo(Short value) {
            addCriterion("oper_result <>", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultGreaterThan(Short value) {
            addCriterion("oper_result >", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultGreaterThanOrEqualTo(Short value) {
            addCriterion("oper_result >=", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultLessThan(Short value) {
            addCriterion("oper_result <", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultLessThanOrEqualTo(Short value) {
            addCriterion("oper_result <=", value, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultIn(List<Short> values) {
            addCriterion("oper_result in", values, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultNotIn(List<Short> values) {
            addCriterion("oper_result not in", values, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultBetween(Short value1, Short value2) {
            addCriterion("oper_result between", value1, value2, "operResult");
            return (Criteria) this;
        }

        public Criteria andOperResultNotBetween(Short value1, Short value2) {
            addCriterion("oper_result not between", value1, value2, "operResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 10 16:51:46 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}