DELETE  FROM TAB_DATA_DICT WHERE DICT_NO in('IF');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','是','是否判断',1,1,'IF');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','否','是否判断',1,2,'IF');

DELETE  FROM TAB_DATA_DICT  WHERE DICT_NO in('SEX');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','男','性别',2,1,'SEX');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','女','性别',2,2,'SEX');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('3','其他','性别',2,3,'SEX');

delete from tab_data_dict where DICT_NO in('ACCUPATION','ACHIEVEMENT_FORM');

insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('1','工人','职业身份','3','1','ACCUPATION');
insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('2','技术人员','职业身份','3','2','ACCUPATION');
insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('3','管理者','职业身份','3','3','ACCUPATION');

insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('1','创新技术、应用新技术成果','体现形式','4','1','ACHIEVEMENT_FORM');
insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('2','创新工艺、提出新的操作法','体现形式','4','2','ACHIEVEMENT_FORM');
insert into tab_data_dict (DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) values ('3','研发新工具、改造老设备','体现形式','4','3','ACHIEVEMENT_FORM');

delete from tab_data_dict where DICT_NO in('LOG_TYPE','LOG_SUB_TYPE');

INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','工作流业务','日志一级分类',5,1,'LOG_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','系统操作','日志一级分类',5,2,'LOG_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('3','接口交互','日志一级分类',5,3,'LOG_TYPE');

INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1.1','流程发起','日志二级分类',6,1,'LOG_SUB_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2.1','登录','日志二级分类',6,2,'LOG_SUB_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2.2','登出','日志二级分类',6,3,'LOG_SUB_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2.3','日常操作','日志二级分类',6,4,'LOG_SUB_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('3.1','短信接口日志','日志二级分类',6,5,'LOG_SUB_TYPE');


delete from TAB_DATA_DICT where DICT_NO='TAB_RESOURCE_TYPE';

INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','系统','用户组类型',7,1,'TAB_RESOURCE_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','模块','用户组类型',7,2,'TAB_RESOURCE_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('3','菜单','用户组类型',7,3,'TAB_RESOURCE_TYPE');


delete from TAB_DATA_DICT where DICT_NO='USER_GROUP_TYPE';

INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','根目录','用户组类型',8,1,'USER_GROUP_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','单位','用户组类型',8,2,'USER_GROUP_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('3','部门','用户组类型',8,3,'USER_GROUP_TYPE');

delete from tab_data_dict where DICT_NO='REPORT_STAUS';

INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('1', '已回复', '困难申报状态', 9, 1,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('2', '已提交', '困难申报状态', 9, 2,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('3', '处理中', '困难申报状态', 9, 3,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('4', '已受理', '困难申报状态', 9, 4,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('5', '已备案', '困难申报状态', 9, 5,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('6', '未发布', '合理化建议状态', 9, 6,  'REPORT_STAUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('7', '已发布', '合理化建议状态', 9, 7, 'REPORT_STAUS');

delete from tab_data_dict where DICT_NO = 'INFO_TYPE';
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1401', '美味食谱', '早知道管理分类', 10, 1,  'INFO_TYPE',14);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1402', '日常通知', '早知道管理分类', 10, 2,  'INFO_TYPE',14);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1403', '大院新闻', '早知道管理分类', 10, 3,  'INFO_TYPE',14);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1404', '便民电话', '早知道管理分类', 10, 4,  'INFO_TYPE',14);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1405', '政策法律', '早知道管理分类', 10, 5,  'INFO_TYPE',14);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1501', '关于介绍', '信息分类', 11, 1,  'INFO_TYPE', 15);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1502', '业务领域', '信息分类', 11, 2,  'INFO_TYPE', 15);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1503', '新闻动态', '信息分类', 11, 3,  'INFO_TYPE', 15);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1504', '联系我们', '信息分类', 11, 4,  'INFO_TYPE', 15);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1601', '合伙人', '法律人员分类', 12, 1,  'INFO_TYPE', 16);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1602', '专职律师', '法律人员分类', 12, 2,  'INFO_TYPE', 16);
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO, PARENT_DICT_TYPE) VALUES ('1603', '辅助人员', '法律人员分类', 12, 3,  'INFO_TYPE', 16);


delete from TAB_DATA_DICT where DICT_NO='EVALUATE_STATUS';

INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('1', '待评价', '评价状态', 13, 1,  'EVALUATE_STATUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('2', '已评价', '评价状态', 13, 2,  'EVALUATE_STATUS');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('4', '发送失败', '评价状态', 13, 4,  'EVALUATE_STATUS');

delete from TAB_DATA_DICT where DICT_NO in('LS_XWFB','SC_ZZD','LS_FZRY');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('14', '陕测早知道', '陕测早知道', 14, 1,  'SC_ZZD');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('15', '律所新闻发布', '律所新闻发布', 15, 2,  'LS_XWFB');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('16', '律所辅助人员', '律所辅助人员', 16, 3,  'LS_FZRY');




DELETE FROM TAB_DATA_DICT WHERE DICT_NO='ACC_TYPE';
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('1','后台系统账户','账户类型',17,1,'ACC_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('2','微信平台账户','账户类型',17,2,'ACC_TYPE');
INSERT INTO TAB_DATA_DICT(DICT_ID,DICT_NAME,REMARK,DICT_TYPE,ORDERNUM,DICT_NO) VALUES('99','其他类型账户','账户类型',17,3,'ACC_TYPE');

delete from TAB_DATA_DICT where DICT_NO='NOTICE_TYPE';

INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('1', '金额消费', '短信类型', 18, 1,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('2', '项目消费', '短信类型', 18, 2,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('3', '充值', '短信类型', 18, 3,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('4', '卡余一类', '短信类型', 18, 4,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('5', '卡余二类', '短信类型', 18, 5,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('6', '卡余三类', '短信类型', 18, 6,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('7', '未体验一类', '短信类型', 18, 7,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('8', '未体验二类', '短信类型', 18, 8,  'NOTICE_TYPE');
INSERT INTO tab_data_dict (DICT_ID, DICT_NAME, REMARK, DICT_TYPE, ORDERNUM,  DICT_NO) VALUES ('9', '专属福利', '短信类型', 18, 9,  'NOTICE_TYPE');
