package priv.guochun.psmc.system.framework.activiti.model;

import java.util.Date;
import java.math.BigDecimal;

public class TFlowConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.tfc_uuid
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private String tfcUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_no
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private String flowNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_cn_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private String flowCnName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_en_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private String flowEnName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_entrance
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private String flowEntrance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_version
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private Float flowVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.create_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.last_update_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.enabled
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private Short enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_flow_config.flow_limit_hour
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	private BigDecimal flowLimitHour;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.tfc_uuid
	 * @return  the value of t_flow_config.tfc_uuid
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public String getTfcUuid() {
		return tfcUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.tfc_uuid
	 * @param tfcUuid  the value for t_flow_config.tfc_uuid
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setTfcUuid(String tfcUuid) {
		this.tfcUuid = tfcUuid == null ? null : tfcUuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_no
	 * @return  the value of t_flow_config.flow_no
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public String getFlowNo() {
		return flowNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_no
	 * @param flowNo  the value for t_flow_config.flow_no
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowNo(String flowNo) {
		this.flowNo = flowNo == null ? null : flowNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_cn_name
	 * @return  the value of t_flow_config.flow_cn_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public String getFlowCnName() {
		return flowCnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_cn_name
	 * @param flowCnName  the value for t_flow_config.flow_cn_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowCnName(String flowCnName) {
		this.flowCnName = flowCnName == null ? null : flowCnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_en_name
	 * @return  the value of t_flow_config.flow_en_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public String getFlowEnName() {
		return flowEnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_en_name
	 * @param flowEnName  the value for t_flow_config.flow_en_name
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowEnName(String flowEnName) {
		this.flowEnName = flowEnName == null ? null : flowEnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_entrance
	 * @return  the value of t_flow_config.flow_entrance
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public String getFlowEntrance() {
		return flowEntrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_entrance
	 * @param flowEntrance  the value for t_flow_config.flow_entrance
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowEntrance(String flowEntrance) {
		this.flowEntrance = flowEntrance == null ? null : flowEntrance.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_version
	 * @return  the value of t_flow_config.flow_version
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public Float getFlowVersion() {
		return flowVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_version
	 * @param flowVersion  the value for t_flow_config.flow_version
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowVersion(Float flowVersion) {
		this.flowVersion = flowVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.create_time
	 * @return  the value of t_flow_config.create_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.create_time
	 * @param createTime  the value for t_flow_config.create_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.last_update_time
	 * @return  the value of t_flow_config.last_update_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.last_update_time
	 * @param lastUpdateTime  the value for t_flow_config.last_update_time
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.enabled
	 * @return  the value of t_flow_config.enabled
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public Short getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.enabled
	 * @param enabled  the value for t_flow_config.enabled
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setEnabled(Short enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_flow_config.flow_limit_hour
	 * @return  the value of t_flow_config.flow_limit_hour
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public BigDecimal getFlowLimitHour() {
		return flowLimitHour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_flow_config.flow_limit_hour
	 * @param flowLimitHour  the value for t_flow_config.flow_limit_hour
	 * @mbg.generated  Tue Apr 10 10:09:00 CST 2018
	 */
	public void setFlowLimitHour(BigDecimal flowLimitHour) {
		this.flowLimitHour = flowLimitHour;
	}
}