package priv.guochun.psmc.system.framework.activiti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.guochun.psmc.system.framework.activiti.model.TFlowConfig;
import priv.guochun.psmc.system.framework.activiti.model.TFlowConfigExample;

public interface TFlowConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    long countByExample(TFlowConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int deleteByExample(TFlowConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int deleteByPrimaryKey(String tfcUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int insert(TFlowConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int insertSelective(TFlowConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    List<TFlowConfig> selectByExample(TFlowConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    TFlowConfig selectByPrimaryKey(String tfcUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") TFlowConfig record, @Param("example") TFlowConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int updateByExample(@Param("record") TFlowConfig record, @Param("example") TFlowConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int updateByPrimaryKeySelective(TFlowConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_config
     *
     * @mbg.generated Mon Apr 09 09:34:21 CST 2018
     */
    int updateByPrimaryKey(TFlowConfig record);
}