package priv.guochun.psmc.system.framework.activiti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.guochun.psmc.system.framework.activiti.model.TFlowInstance;
import priv.guochun.psmc.system.framework.activiti.model.TFlowInstanceExample;

public interface TFlowInstanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	long countByExample(TFlowInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int deleteByExample(TFlowInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int deleteByPrimaryKey(String tfiUuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int insert(TFlowInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int insertSelective(TFlowInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */List<TFlowInstance> selectByExample(TFlowInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	TFlowInstance selectByPrimaryKey(String tfiUuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */int updateByExampleSelective(@Param("record") TFlowInstance record,@Param("example") TFlowInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */int updateByExample(@Param("record") TFlowInstance record,@Param("example") TFlowInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int updateByPrimaryKeySelective(TFlowInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_flow_instance
	 * @mbg.generated  Tue Apr 10 16:16:28 CST 2018
	 */
	int updateByPrimaryKey(TFlowInstance record);
}