package priv.guochun.psmc.system.common.vcode.model;

import java.util.Date;

public class TabVerificationCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.uuid
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.type
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private Long type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.state
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private Long state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.create_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.effective_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private Long effectiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tab_verification_code.ip
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	private String ip;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.uuid
	 * @return  the value of tab_verification_code.uuid
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.uuid
	 * @param uuid  the value for tab_verification_code.uuid
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid == null ? null : uuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.type
	 * @return  the value of tab_verification_code.type
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public Long getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.type
	 * @param type  the value for tab_verification_code.type
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setType(Long type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.state
	 * @return  the value of tab_verification_code.state
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public Long getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.state
	 * @param state  the value for tab_verification_code.state
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setState(Long state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.code
	 * @return  the value of tab_verification_code.code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.code
	 * @param code  the value for tab_verification_code.code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.create_time
	 * @return  the value of tab_verification_code.create_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.create_time
	 * @param createTime  the value for tab_verification_code.create_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.effective_time
	 * @return  the value of tab_verification_code.effective_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public Long getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.effective_time
	 * @param effectiveTime  the value for tab_verification_code.effective_time
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setEffectiveTime(Long effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tab_verification_code.ip
	 * @return  the value of tab_verification_code.ip
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tab_verification_code.ip
	 * @param ip  the value for tab_verification_code.ip
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}
}