package priv.guochun.psmc.system.common.log.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.guochun.psmc.system.common.log.model.TSysOperLog;
import priv.guochun.psmc.system.common.log.model.TSysOperLogExample;

public interface TSysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    long countByExample(TSysOperLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    int deleteByExample(TSysOperLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    int insert(TSysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    int insertSelective(TSysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    List<TSysOperLog> selectByExample(TSysOperLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSysOperLog record, @Param("example") TSysOperLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_oper_log
     *
     * @mbg.generated Tue Apr 10 16:51:46 CST 2018
     */
    int updateByExample(@Param("record") TSysOperLog record, @Param("example") TSysOperLogExample example);
}