package priv.guochun.psmc.system.common.vcode.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import priv.guochun.psmc.system.common.vcode.model.TabVerificationCode;
import priv.guochun.psmc.system.common.vcode.model.TabVerificationCodeExample;

public interface TabVerificationCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int countByExample(TabVerificationCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int deleteByExample(TabVerificationCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int deleteByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int insert(TabVerificationCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int insertSelective(TabVerificationCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	List<TabVerificationCode> selectByExample(TabVerificationCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	TabVerificationCode selectByPrimaryKey(String uuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TabVerificationCode record,
			@Param("example") TabVerificationCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int updateByExample(@Param("record") TabVerificationCode record,
			@Param("example") TabVerificationCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int updateByPrimaryKeySelective(TabVerificationCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tab_verification_code
	 * @mbggenerated  Sun May 27 18:41:10 CST 2018
	 */
	int updateByPrimaryKey(TabVerificationCode record);
}